# Generated by Django 4.1 on 2022-08-21 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название задачи')),
                ('task_description', models.CharField(max_length=2000, verbose_name='Описание задачи')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название задания')),
                ('todo_description', models.CharField(max_length=4000, verbose_name='Описание задания')),
                ('parent_todo', models.IntegerField(default=0, verbose_name='Родительское задание')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.task')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
